trading_pairs:
  - BTC-USDT-SWAP
  - ETH-USDT-SWAP
  - SOL-USDT-SWAP
  - BNB-USDT-SWAP
  - LINK-USDT-SWAP
  - SUI-USDT-SWAP
  - DOGE-USDT-SWAP
  - XRP-USDT-SWAP
leverage:
  BTC: 100
  ETH: 100
  SOL: 50
  BNB: 50
  LINK: 50
  SUI: 50
  DOGE: 50
  XRP: 50
timeframes:
  - 4H
  - 1H
  - 30M
  - 15M
  - 5M